obj-$(CONFIG_LWIP)	+=	autoip.o
obj-$(CONFIG_LWIP)	+=	icmp.o
obj-$(CONFIG_LWIP)	+=	igmp.o
obj-$(CONFIG_LWIP)	+=	inet.o
obj-$(CONFIG_LWIP)	+=	inet_chksum.o
obj-$(CONFIG_LWIP)	+=	ip_addr.o
obj-$(CONFIG_LWIP)	+=	ip.o
obj-$(CONFIG_LWIP)	+=	ip_frag.o
