obj-$(CONFIG_LWIP)	+=	api_lib.o
obj-$(CONFIG_LWIP)	+=	api_msg.o
obj-$(CONFIG_LWIP)	+=	err.o
obj-$(CONFIG_LWIP)	+=	netbuf.o
obj-$(CONFIG_LWIP)	+=	netdb.o
obj-$(CONFIG_LWIP)	+=	netifapi.o
obj-$(CONFIG_LWIP)	+=	sockets.o
obj-$(CONFIG_LWIP)	+=	tcpip.o
